import streamlit as st
import geopandas as gpd
import pandas as pd
import numpy as np
import os
import time

st.set_page_config(page_title="Intelligent Dispatch", layout="wide", page_icon="🔔")

st.title("🔔 Geospatial Alert Dispatcher")
st.markdown("""
**Automated Proximity Routing.** This module identifies the nearest Forest Officer to a confirmed threat and prepares a localized enforcement brief.
""")

# --- 1. MOCK OFFICER DATABASE ---
# In production, this would be your 'Forest_Officers' SQL table
OFFICERS = [
    {"name": "R. Karthik (Range A)", "email": "karthikratnala45@gmail.com", "lat": 24.5854, "lon": 73.7125, "station": "Udaipur North"},
    {"name": "Officer Sharma (Range B)", "email": "sharma_forest@rajasthan.gov.in", "lat": 26.9124, "lon": 75.7873, "station": "Jaipur West"},
    {"name": "Officer Meena (Range C)", "email": "meena_aravalli@gov.in", "lat": 28.4595, "lon": 77.0266, "station": "Gurugram South"},
]

# --- 2. DISTANCE CALCULATION FUNCTION ---
def calculate_distance(lat1, lon1, lat2, lon2):
    # Haversine formula to find distance between two points in km
    R = 6371 
    dlat = np.radians(lat2 - lat1)
    dlon = np.radians(lon2 - lon1)
    a = np.sin(dlat/2)**2 + np.cos(np.radians(lat1)) * np.cos(np.radians(lat2)) * np.sin(dlon/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))
    return R * c

@st.cache_data
def load_alert_data():
    path = "outputs/alerts.geojson"
    if not os.path.exists(path): return None
    return gpd.read_file(path)

alerts_gdf = load_alert_data()

if alerts_gdf is None or alerts_gdf.empty:
    st.warning("No active threats found for dispatch.")
else:
    col_list, col_action = st.columns([1, 1.5])

    with col_list:
        st.subheader("📍 Target Hotspot")
        selected_grid = st.selectbox("Select Verified Grid ID", options=alerts_gdf['grid_id'].unique())
        
        target = alerts_gdf[alerts_gdf['grid_id'] == selected_grid].iloc[0]
        t_lat, t_lon = target.geometry.y, target.geometry.x
        
        st.error(f"**Detected Trigger:** {target['Drift_Reason']}")
        st.write(f"**Coordinates:** {t_lat:.4f}, {t_lon:.4f}")

        # --- NEAREST OFFICER LOGIC ---
        st.markdown("---")
        st.subheader("🕵️ Finding Nearest Officer...")
        
        # Calculate distances to all officers
        distances = []
        for off in OFFICERS:
            dist = calculate_distance(t_lat, t_lon, off['lat'], off['lon'])
            distances.append(dist)
        
        # Get index of the minimum distance
        nearest_idx = np.argmin(distances)
        nearest_officer = OFFICERS[nearest_idx]
        min_dist = distances[nearest_idx]

        st.success(f"**Closest Officer Found:** {nearest_officer['name']}")
        st.write(f"**Distance to Hotspot:** {min_dist:.2f} km")
        st.write(f"**Assigned Station:** {nearest_officer['station']}")

    with col_action:
        st.subheader("📨 Automated Dispatch")
        
        with st.form("dispatch_form"):
            recipient = st.text_input("Designated Recipient", value=nearest_officer['email'])
            
            subject = f"ACTION REQUIRED: Drift Detected in {nearest_officer['station']} Range"
            
            message_body = f"""OFFICIAL DISPATCH: ARAVALLI INTELLIGENCE
--------------------------------------------------
URGENT: Man-made ecological drift confirmed within your range.

TARGET ID: {selected_grid}
LOCATION: {t_lat:.4f}, {t_lon:.4f}
PROXIMITY TO YOUR STATION: {min_dist:.2f} km
SEVERITY: {target['Severity_Score']}%

AI ANALYSIS: {target['Drift_Reason']}

The system has identified you as the NEAREST responding officer. 
Please confirm receipt and initiate ground verification.
--------------------------------------------------
Generated by: Aravalli Intelligence System
"""
            
            email_text = st.text_area("Enforcement Brief", value=message_body, height=300)
            
            if st.form_submit_button("🚀 Send Targeted Alert"):
                with st.spinner("Routing alert through GIS network..."):
                    time.sleep(1.5)
                    st.success(f"✅ Alert sent to {nearest_officer['name']} at {recipient}")
                    st.balloons()